### ISSUE TITLE
Specify the target audience for the document

### ISSUE THREAD

**Issue by fulldecent** [Arianee/docs#25]
This will help guide this review. But more importantly it will help attract high-quality contribution to the document.

Recommendation:

> This documentation is for contributors to applications released by the Arianee project (published under https://github.com/Arianee/) and third-party applications that work with Arianee.

**Comment by fulldecent** [comment]
Without explaining the audience, it is unclear if this is aimed at third-party developers (who only care about the JS API and very likely won't get involved with blockchain parts) or core developers at Arianee.

But it surely isn't aimed at users and brands.

**Comment by ArnaudPrigent** [comment]
New text:

The Arianee project mission is to provide the valuable products’ ecosystem a secure environment to create and manage certificates.

This documentation is dedicated to third-party developers who want to focus on the application layer and quickly deliver integrated solutions based on standardized certificates.

**Comment by fulldecent** [comment]
Great, thank you.
