### ISSUE TITLE
CI deploy after PR

### ISSUE THREAD

**Issue by gnarco** [Arianee/docs#3]
After a PR on Docs, it should deploy docs to productions.

Command line that I currently use :
GIT_USER=gnarco   CURRENT_BRANCH=master   USE_SSH=true   npm run publish-gh-pages

**Comment by xiaoshan-j** [comment]
Hi, how Arianee make money from this ?

**Comment by gnarco** [comment]
Hi @xiaoshan-j 

You should read : https://docs.arianee.org
Evrything is explained

Aex
