### ISSUE TITLE
Who is Arianee SAS?

### ISSUE THREAD

**Issue by fulldecent** [Arianee/docs#8]
An entity "Arianee SAS" is referenced without introduction at https://docs.arianee.org/docs/howToProceed

What is this entity?

---

Also, please say the name of the entity which publishes docs.arianee.org and arianee.org here:

<img width="1446" alt="Screen Shot 2019-11-03 at 10 29 02" src="https://user-images.githubusercontent.com/382183/68087509-c9d57c80-fe24-11e9-8dd9-f23553451fbb.png">

Please use the full, legal name of the entity. Bonus points if you will mention the corporation registration number and jurisdiction.

Also, update the WHOIS registration to match.

Too many blockchain projects register their company in weird ways, or not at all. In contrast, we are a professional organization and we should have a MUCH higher standard than blockchain projects. Our benchmark should be companies that have existed 50 years or more.

**Comment by gnarco** [comment]
I updated the copyright

What do you mean about the whois.

You talk about this : http://whois.domaintools.com/arianee.org  and ask for unhide info ?

**Comment by fulldecent** [comment]
Yes, that is what I'm referring to.
